### ISSUE TITLE
AZ-120_Lab03a-HANA_HA_Infrastructure_Deployment error in the end of the lab

### ISSUE THREAD

**Issue by monsash** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#10]
Hi,

In the Lab 03a, named HANA HA Infrastructure Deployment, I deployed some virtual machines, including  i20-db-0 and 
i20-db-1 (They are both configured with pacemaker configuration). I used this guide:

https://github.com/MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads/blob/master/Instructions/AZ-120_Lab03a-HANA_HA_Infrastructure_Deployment.md

All the steps ran good and without any error. However, when I try to see the Suse HA Management Web Page, It prompts me the followings error message:

![image](https://user-images.githubusercontent.com/33970226/104400207-eabd5580-5530-11eb-9e1a-ca6c04d29d82.png)

![image](https://user-images.githubusercontent.com/33970226/104400282-03c60680-5531-11eb-90a7-248272319775.png)

Any idea what happened? Did I forgot something? What do I do to fix it?

Let me know any news

Regards,
Leopoldo Morales

**Comment by polichtm** [comment]
Hi Leopoldo,
could you post the screenshot of the Status page?
rgds
Marcin

**Comment by monsash** [comment]
Hi,

The first image is the status page:

![image](https://user-images.githubusercontent.com/33970226/104401533-248f5b80-5533-11eb-983d-c7e54a743309.png)

Let me know if you need anything else.

Regards,
Leopoldo

**Comment by polichtm** [comment]
Hi Leopoldo,
let me try to duplicate this issue
rgds
Marcin

**Comment by monsash** [comment]
Thank you :) let me try too to duplicate the issue and show you in a screenshot the complete Dashboard

**Comment by monsash** [comment]
Hi,

I tried to duplicate again the lab guide and again I received the same error message:

![image](https://user-images.githubusercontent.com/33970226/104537967-bbbee680-55f9-11eb-8af1-6cbeb2374c85.png)

Did you see something? Do I have to do something else?

Let me know anything you need.

Regards
Leopoldo Morales

**Comment by polichtm** [comment]
Hi Leopoldo,
I have reproduced the issue and should have the fix ready within the next day or two...
rgds
Marcin

**Comment by polichtm** [comment]
Hi Leopoldo,
this has been addressed - pls use the updated instructions and let us know if you need any additional assistance concerning this lab
rgds
Marcin
