### ISSUE TITLE
Lab01 Ex02 Task3 - ssh session keeps asking for password

### ISSUE THREAD

**Issue by dvimacedo** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#101]
# Module/Lab: 01
#### Step: 30

Description of issue

After following all the steps of task 3, when testing the ssh access from one machine to another, it keeps asking for the password

Repro steps:

all steps of task 3, leading to step 30

### Relevant screenshots

![image](https://github.com/user-attachments/assets/8b5f1b2a-f70c-4100-ace8-da0f62b80e10)

**Comment by eric-camplin** [comment]
I have repo of issue - currently troubleshooting for a solution.
