### ISSUE TITLE
In Lab 1b: Implementing Windows clustering on Azure VMs

### ISSUE THREAD

**Issue by sathishneelam** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#11]
Task 1: Deploy a pair of Azure VMs running highly available Active Directory domain controllers by using an Azure Resource Manager template

While I'm deploying the template it's failing with below error

![image](https://user-images.githubusercontent.com/58003174/115517501-d19d1100-a2a4-11eb-862b-aefb5bde40cd.png)

can you please check on this..?

**Comment by GhumanNavneet** [comment]
any update on this

**Comment by polichtm** [comment]
Hi Ghuman and Satish,
pls give this another try. The deployment might fail initially, but once you remove the Custom Script Extension and redeploy the template, it should succeed - as per the screenshot below

![image](https://user-images.githubusercontent.com/10284906/117228698-8c6df880-ade7-11eb-984f-bf671dca029a.png)

rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
