### ISSUE TITLE
Any reason why user cannot do the exercises from a macOS or Linux laptop?

### ISSUE THREAD

**Issue by murmelsson** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#13]
Are yous sure this is actually required: "A lab computer running Windows 10, Windows Server 2016, or Windows Server 2019 with access to Azure". For example, the Cloud Shell works for example on macOS Chrome browser just fine.

**Comment by polichtm** [comment]
valid point - updated
rgds
Marcin
