### ISSUE TITLE
Lab 3b: Implement SAP architecture on Azure VMs running Windows #8

### ISSUE THREAD

**Issue by sathishneelam** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#14]
Lab 3b: Implement SAP architecture on Azure VMs running Windows

In Exercise 1: Provision Azure resources necessary to support highly available SAP NetWeaver deployments

Task 5: Deploy the Scale-Out File Server (SOFS) cluster

Here the deployment prolonged as not expected and also the deployment got failed

![image](https://user-images.githubusercontent.com/58003174/117123870-36805d00-adb5-11eb-8870-3b11c1922816.png)

I tried performing the below step as @polichtm Marcin suggested this in one of the closed issues

steps:

review the deployment details and identify the VM(s) where the installation of the CustomScriptExtension failed (according to the screenshot, that's i20-s2d-0 in your case)
in the Azure portal, navigate to the blade of the VM(s) you identified in the previous step, select Extensions, and from the Extensions blade, remove the CustomScript extension
in the Azure portal, navigate to the AZ12003B-SAP-RG resource group blade, select Deployments, select the link to the failed deployment, and select Redeploy
to redeploy, you will need to select the target resource group (AZ12003B-SAP-RG) and provide the password for the root account (Pa55w.rd1234).

But still, I'm facing the same issue

Can you please look into it.?

Thanks & Regards
Sathish Neelam

**Comment by polichtm** [comment]
Hi Sathish,
investigating...
rgds
Marcin

**Comment by polichtm** [comment]
As mentioned in #12, this works fine for me - pls give another try and, if needed, try redeploying a few times
![image](https://user-images.githubusercontent.com/10284906/117231942-47999000-adee-11eb-8ea9-8cee011b0ab2.png)

rgds
Marcin

**Comment by sathishneelam** [comment]
@polichtm the one which you mentioned is a different temple from Exercise 1 Task 1: Deploy a pair of Azure VMs running highly available Active Directory domain controllers by using an Azure Resource Manager template

 We're facing the issue with this template i.e., https://github.com/robotechredmond/301-storage-spaces-direct-md

In Exercise 1: Provision Azure resources necessary to support highly available SAP NetWeaver deployments

**Task 5**: Deploy the Scale-Out File Server (SOFS) cluster

**Comment by polichtm** [comment]
This works for me as well...
![image](https://user-images.githubusercontent.com/10284906/117382357-534b8c00-aeac-11eb-8d94-ddf34b6d294c.png)
Pls give it another try
rgds
Marcin

**Comment by polichtm** [comment]
Pls provide the logs of the most recent update you tried
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
