### ISSUE TITLE
Lab 3a: Implement SAP architecture on Azure VMs running Linux

### ISSUE THREAD

**Issue by GhumanNavneet** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#18]
Exercise 1 Task 2 link is incorrect please update it https://github.com/Azure/azure-quickstart-templates/tree/master/sap-3-tier-marketplace-image-md

Here is the correct link
https://github.com/chagarw/azure-quickstart-templates/tree/master/sap-3-tier-marketplace-image

**Comment by GhumanNavneet** [comment]
Can you update this and conform if this is working ?? because it is not working for us

please share the solution

**Comment by polichtm** [comment]
Hi Ghuman,
It's actually https://github.com/Azure/azure-quickstart-templates/tree/master/application-workloads/sap/sap-3-tier-marketplace-image-md 
Pls use this link and let us know about the outcome
rgds
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response
