### ISSUE TITLE
 Lab3b: Implement SAP architecture on Azure VMs running Windows

### ISSUE THREAD

**Issue by GhumanNavneet** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#19]
Hi Team

we get this deployment error 👎 every time in this lab when we do the testing:

![image](https://user-images.githubusercontent.com/33318387/129542092-01ad87f1-37f6-4899-b8d2-909437bedc6a.png)

Please resolve or give correct instructions

**Comment by polichtm** [comment]
Pls provide the exercise, task, and step number that results in this error
rgds
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response
