### ISSUE TITLE
AZ-120_Lab01b-Azure_VM_Windows_Clustering

### ISSUE THREAD

**Issue by PremSharma2025** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#2]
Dear concern,
     I am getting error while using lab : - AZ-120_Lab01b-Azure_VM_Windows_Clustering at below step.Its giving error while pasting below link into the _artifacts Location

_artifacts Location: **https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/active-directory-new-domain-ha-2-dc

![image](https://user-images.githubusercontent.com/46988451/75669159-8db20b80-5ca0-11ea-9e03-262f3a64fb87.png)

**Comment by polichtm** [comment]
As per instructions, you are not supposed to set this value - instead, leave its default in place
rgds
Marcin

**Comment by PremSharma2025** [comment]
Hi,
 thanks, but in both way either using default or pasting in it getting same error.

**Comment by polichtm** [comment]
Pls post the error message
rgds
Marcin

**Comment by polichtm** [comment]
Pls include a trailing backslash and give it another try
https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/active-directory-new-domain-ha-2-dc/
rgds
Marcin
