### ISSUE TITLE
Lab 3a: Exercise 1 Task 2 Step 6: Are we *certain* the current _artifacts Location URL is correct?

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#23]
In Lab 3a: Exercise 1 Task 2 Step 6, this is currently given as the _artifacts Location: **https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/sap-3-tier-marketplace-image-md/**

I have tried several times testing yesterday and today from fresh lab instances and if I use the value for artifacts location currently given I consistently get all 6 of the <vm>/CustomScript resources all failing:

![image](https://user-images.githubusercontent.com/49700217/135134735-b07b457d-4dd8-4531-8ad2-cecfb73276b3.png)

They all have this error, which seems to basically boil down to a '404' - really making me suspicious the URL for artifacts is not pointing to a correct location, and the steps in the 'Note: if the deployment fails' are of no use:

![image](https://user-images.githubusercontent.com/49700217/135134970-1ee44864-bcbc-465d-99da-e7244df31843.png)

On the other hand, if I use _artifacts Location: **https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/application-workloads/sap/sap-3-tier-marketplace-image-md/** -- a coworker recommended that one - and when using it deploy *mostly* succeed.  I say mostly, because I have had some unexpectedly random results when trying multiple iterations of testing from fresh lab start using that URL.

In some cases the resources all deploy error free.  In other cases one, or sometimes 2 (usually i20-db-0, and/or i20-db-1) /CustomScript will fail with nasty errors that appear like so:

![image](https://user-images.githubusercontent.com/49700217/135132499-08db78af-86b9-4862-a07b-089ac67a31ef.png)

In the case where I get those nasty errors - often (but not always) the steps in the 'Note: if the deployment fails' will be sufficient to recover, redeploy, and get a success.

In any case, to sum up:  I think there is an issue w/the current URL given, and I am not 100% certain what the URL *should* be....just that there seems to be at least one that mostly succeeds.

**Comment by polichtm** [comment]
Appreciate the detailed explanation.
looking into this
rgds
Marcin

**Comment by polichtm** [comment]
I validated that the link you provided works as expected and updated the content accordingly. In case you run into an issue with installation of the VM extension, pls uninstall it and try redeploying (as stated in the instructions)
rgds
Marcin

**Comment by polichtm** [comment]
the lab instructions have been retested recently. Pls let us know if you're still running into any issues
rgds
Marcin
