### ISSUE TITLE
Issue: In lab 3b(Implement SAP architecture on Azure VMs running Windows)

### ISSUE THREAD

**Issue by GhumanNavneet** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#3]
In lab 3b(Implement SAP architecture on Azure VMs running Windows)
 
In Exercise 1, Task 3, Step 2
On the page titled SAP NetWeaver 3-tier compatible template using a Marketplace image - MD,  When I click “Deploy to Azure” it is not redirecting the page to the Azure portal.
Link: https://github.com/Azure/azure-quickstart-templates/tree/master/sap-3-tier-marketplace-image-md

In Exercise 1, Task 5
Faced an error while deploying the template ” 301-storage-spaces-direct-md” 
"The DSC Extension failed to execute: Error downloading https://raw.githubusercontent.com/robotechredmond/301-storage-spaces-direct-md/master/dsc/prep-s2d.ps1.zip

**Comment by polichtm** [comment]
Hi Ghuman,
I updated instructions regarding the first issue - but I cannot reproduce the second one. Would you mind giving it another try? 
The DSC extension archive is accessible
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
