### ISSUE TITLE
Issue in Lab 3b: Implement SAP architecture on Azure VMs running Windows

### ISSUE THREAD

**Issue by shivashant25** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#45]
In Exercise 1> Task 4> step 5, The deployment is failing with the following error mentioned below:

ERROR MESSAGE:
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "VMExtensionProvisioningError",
      "message": "VM has reported a failure when processing extension 's2dPrep'. Error message: \"DSC Configuration 'PrepS2D' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_xWaitForADDomain  failed to execute Set-TargetResource functionality with error message: Domain 'adatum.com' NOT found after 20 attempts.  The SendConfigurationApply function did not succeed.\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot "
    }
  ]
}

![image](https://user-images.githubusercontent.com/81952290/181777472-4dee4d39-70cf-469a-996a-4264bf96e7fa.png)

Kindly check on this issue.

**Comment by polichtm** [comment]
Hi Shivashant,
pls connect to the newly deployed VMs and let us know whether:
- you can connect to the adatum.com domain controllers via their IP addresses
- if so, whether you can resolve the names associated with the adatum.com domain
- if so, whether you can join the domain manually
rgds
Marcin

**Comment by shivaudari** [comment]
Hi Marcin,

This is to update you that, we were able to communicate and join the VM's to domain using PS command (_add-computer –domainname "DomainName"_).

PS: Uninstalled the failed Extensions on both VM's.

Thank you!

**Comment by polichtm** [comment]
Hi Shivashant,
we'll be updating instructions to account for this
rgds
Marcin

**Comment by polichtm** [comment]
The instructions have been updated to provide a fix for this issue
rgds
Marcin

**Comment by akn9050** [comment]
@polichtm deployment is still failing, we tried to re-deploy the failed template multiple times but issue still persist.
