### ISSUE TITLE
Issues in Lab 4a: Implement SAP architecture on Azure VMs running Linux

### ISSUE THREAD

**Issue by kumud-sharma** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#46]
In Exercise 2> Task 2> step 5> Not able to connect via SSH for i20-db-0 and  i20-db-1 from the RDP session to az12003a-vm0.

**Comment by polichtm** [comment]
Hi Kumud,
pls clarify what specifically is failing. Is this connectivity (can you ping the target VMs) or authentication?
rgds
Marcin

**Comment by shivashant25** [comment]
Hi @polichtm , We re-tested the lab and were able to fix the issue. Closing this issue. Thank you

**Comment by polichtm** [comment]
Excellent  - appreciated
rgds
Marcin
