### ISSUE TITLE
Template deployment is failing for Scale-Out File Server (SOFS) cluster deployment 

### ISSUE THREAD

**Issue by akn9050** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#47]
hi @polichtm ,

The ARM template deployment on [Exercise 1 Task 4](https://github.com/MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads/blob/master/Instructions/AZ-120_Lab03b-SQL_HA_Infrastructure_Deployment.md#task-4-deploy-the-scale-out-file-server-sofs-cluster) is still failing for Scale-Out File Server (SOFS) cluster deployment, with below error message. 

Can you please check on it
{
    "status": "Failed",
    "error": {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 's2dPrep'. Error message: \"DSC Configuration 'PrepS2D' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_xWaitForADDomain  failed to execute Set-TargetResource functionality with error message: Domain 'adatum.com' NOT found after 20 attempts.  The SendConfigurationApply function did not succeed.\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot "
    }
}

**Comment by polichtm** [comment]
Hi Amit,
just to make sure - have you followed the updated instructions posted in this repo?
rgds
Marcin

**Comment by akn9050** [comment]
hi @polichtm , yes I followed the updated instructions posted in this repo.

**Comment by akn9050** [comment]
Hey @polichtm, I tested the whole lab again and it worked

**Comment by polichtm** [comment]
Excellent - appreciate the follow up
rgds
Marcin
