### ISSUE TITLE
M02-Unit 2A - Instructions need some updates

### ISSUE THREAD

**Issue by v-asamim** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#48]
# Module: M02-Unit 2A
#### Step: 00

Description of issue
 Instructions are different from Azure portal. Instructions docs needs some updating.

Repro steps:

1. Exercise 1, Task 1, Create a Virtual Machine, Disks, Step 1 -> "Encryption type" from instructions should change to "Key management"
2. Exercise 1, Task 1, Create a Virtual Machine, Networking, Step 2 -> "Address space" from instructions is not in Azure Portal
3. Exercise 1, Task 1, Create a Virtual Machine, Management, Step 1 -> "Boot diagnostics" from instructions is not in Azure Portal
4. Exercise 1, Task 1, Create a Virtual Machine, Management, Step 1 -> "OS guest diagnostics" from instructions is not in Azure Portal
5. Exercise 3, Task 2, Load Balancers, Add backend pool, Step 2 -> Instructions are different from Azure portal.
6. Exercise 3, Task 2, Load Balancers, Inbound rules, Step 3 -> Instructions are different from Azure portal.

### Lab

Lab 2a: Implement Linux clustering on Azure VMs

### Relevant screenshots

1. Exercise 1, Task 1, Create a Virtual Machine, Disks, Step 1, Screenshots
![image](https://user-images.githubusercontent.com/111972688/200295947-054aac9c-d8df-4538-b3d1-66c60c8ce679.png)

2. Exercise 1, Task 1, Create a Virtual Machine, Networking, Step 2, Screenshots
![image](https://user-images.githubusercontent.com/111972688/200301360-c7821e75-8929-4325-962e-308a021cd478.png)

3. Exercise 1, Task 1, Create a Virtual Machine, Management, Step 1
4. Exercise 1, Task 1, Create a Virtual Machine, Management, Step ,1 Screenshots
![image](https://user-images.githubusercontent.com/111972688/200301383-0c8b2593-dcb5-404c-8df9-e04da047d3a5.png)

5. Exercise 3, Task 2, Load Balancers, Add backend pool, Step 2, Screenshots
![image](https://user-images.githubusercontent.com/111972688/200301402-54ca3803-c75a-4a23-a967-e1e9051d4796.png)

6. Exercise 3, Task 2, Load Balancers, Inbound rules, Step 3, Screenshots
![image](https://user-images.githubusercontent.com/111972688/200301465-4516b77e-11ab-48b5-965b-de82126c3235.png)

**Comment by v-asamim** [comment]
@eric-camplin please verify that you can see the same issues, there are difference in azure portal at sometimes.

**Comment by polichtm** [comment]
Hi Abdullah
we're in the process of updating the content to account for your feedback
rgds
Marcin

**Comment by polichtm** [comment]
Hi Abdullah
this is completed
rgds
Marcin

**Comment by v-asamim** [comment]
> Hi Abdullah this is completed rgds Marcin

Thank you
