### ISSUE TITLE
M01-Unit 1B - Instructions need some updates

### ISSUE THREAD

**Issue by v-asamim** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#49]
# Module: M01-Unit 1B
#### Step: 04

Description of issue
 Instructions are different from Azure portal. Instructions docs needs some updating.

Repro steps:

1. Exercise 3, Task 2, Load balancers, Add backend pools, Step 4 -> "Backend pool configuration" is not in the Instructions.
 and "IP addresses" part need update in the Instructions.

### Lab

Lab 1b: Implement Windows clustering on Azure VMs

### Relevant screenshots

1. Exercise 3, Task 2, Load balancers, Add backend pools, Step 4, Screenshots
![image](https://user-images.githubusercontent.com/111972688/200306429-7d6ed8da-2ab0-466d-89c0-5f547e58cfcb.png)

**Comment by polichtm** [comment]
Hi Abdullah
updated 
rgds
Marcin

**Comment by v-asamim** [comment]
> Hi Abdullah updated rgds Marcin

Thank you
