### ISSUE TITLE
Load balancer frontend IP

### ISSUE THREAD

**Issue by rahulShirwadkar** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#5]
page number 16:
Frontend IP address: 
Wrong**192.168.0.240 (In linux lab used) 
correct: **10.0.1.240 ( In windows lab need to use)

Page number 20:
wrong: 
1.  Within the RDP session to az12001b-vm2, ensure that you can establish **_SSH_** session to both az12001b-cl-vm0 and az12001b-cl-vm1 via their private IP addresses (10.0.1.4 and 10.0.1.5, respectively). 

correct:
1.  Within the RDP session to az12001b-vm2, ensure that you can establish **_RDP_** session to both az12001b-cl-vm0 and az12001b-cl-vm1 via their private IP addresses (10.0.1.4 and 10.0.1.5, respectively).

**Comment by polichtm** [comment]
valid point - updated
rgds
Marcin
