### ISSUE TITLE
M01-Unit 1B - Deployment failed error

### ISSUE THREAD

**Issue by v-asamim** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#50]
# Module: M01-Unit 1B
#### Step: 04

Description of issue
 An Error found "Deployment to resource group az12001b-ad-RG failed".

Repro steps:

1. Exercise 1, Task 1, Custom Deployment, Step 4 -> Deployment to resource group az12001b-ad-RG failed.

### Lab

Lab 1b: Implement Windows clustering on Azure VMs

### Relevant screenshots

1. Exercise 1, Task 1, Custom Deployment, Step 4, Screenshots

![image](https://user-images.githubusercontent.com/111972688/200316079-aa07f400-666b-445e-999b-c9124b86e8a5.png)
![image](https://user-images.githubusercontent.com/111972688/200316138-f637f732-531a-42bb-ab24-baad104529fd.png)
![image](https://user-images.githubusercontent.com/111972688/200316160-48e69d36-8096-435f-b5ae-37bad3c26d46.png)

**Comment by polichtm** [comment]
Hi Abdullah,
if you encounter an error triggered by a DSC extension, then pls follow the guidance included in the lab instructions. This should allow you to complete the deployment successfully:
![image](https://user-images.githubusercontent.com/10284906/204057208-b6fc8801-3b9c-4fde-bcd0-63ec0ec35f8e.png)

rgds
Marcin
