### ISSUE TITLE
AZ-120_Lab01a-Azure_VM_Linux_Clustering.md - Azure changes, minor issue(s)

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#51]
The following items were noted in a recent QA as places where Azure UI/click throughs have changed and may need to be updated to match:

-**Exercise 1, Task 1, Step 10:** Should say select Next: Monitoring > and then select Next: Advanced >.  Also, there was no option to not Enable basic plan for free.

-**Exercise 1, Task 1, Step 17:** Should say select Next: Monitoring > and then select Next: Advanced >.  Also, there was no option to not Enable basic plan for free.

-**Exercise 3, Task 2, Step 3:** This step "Click Next: Frontend IP Configuration. On the Frontend IP configuration screen, click Add a frontend IP configuration and then click Add." 
should be "Click Next: Frontend IP Configuration. On the Frontend IP configuration screen, click Add a frontend IP configuration, specify the following settings and then click Add."

-**Exercise 3, Task 4, Step 5:** Should say select Next: Monitoring > and then select Next: Advanced >.  Also, there was no option to not Enable basic plan for free nor Enable backup nor Guest OS updates. 

Also, in md header/title it says 'Lab **2a**: Implement Linux clustering on Azure VMs' although the document is indicating 'Lab**01a**'.  Probably as a result of evolving naming conventions as course has grown and changed...slight chance it might confuse someone who may think there were labs missing?

**Comment by polichtm** [comment]
appreciate the feedback - under review
rgds
Marcin

**Comment by TesterTesterson1004** [comment]
I'm testing using an ALHs Cloudslice platform and just noticed that in a different lab it *does* have the 'Enable basic plan for free' option to disable, so it is highly likely this is ALH-specific behavior that varies based on type of subscription in use - thus those 2 specific references can likely be ignored.  Apologies for red herring!

**Comment by eric-camplin** [comment]
Thank you for summitting issues.
