### ISSUE TITLE
AZ-120_Lab01b-Azure_VM_Windows_Clustering.md - Should log in as adatum\student?

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#52]
I could easily be missing something, but when I run the command in Exercise 2, Task 3, Step 1, (after earlier logging in to the VMs literally as 'student') the command runs successfully on VM0, however it fails with error when trying to auth to VM1 and run the same command.

I didn't get a screenshot of the error just now, however it is exactly the sort of error one would assume you would get if you were logged on to [machinename]\student as opposed to an account such as [domainname]\student that has perms on both VMs and thus can connect back and forth.  The command/reboot *does* work on VM0, but in order to get it to work whilst logged in as plain 'student' account...one has to then connect separately to the VM1 VM and re-run the powershell commands.  

However, since the instructions seem to assume this command will be only run once on VM0 to install to both VMs/reboot both VMs, I *think* that the earlier steps that reference logins should not be like so:

1.  From the **az12001b-cl-vm0** blade, connect to the virtual machine guest operating system by using Remote Desktop. When prompted to authenticate, provide the following credentials:

    -   User name: **Student**

    -   Password: **Pa55w.rd1234**

But instead be like so:

1.  From the **az12001b-cl-vm0** blade, connect to the virtual machine guest operating system by using Remote Desktop. When prompted to authenticate, provide the following credentials:

    -   User name: **Adatum\Student**

    -   Password: **Pa55w.rd1234**

**Comment by polichtm** [comment]
Appreciate the suggestions. This module is being rewritten to incorporate a Bicep-based deployment - more information to follow
rgds
Marcin

**Comment by polichtm** [comment]
addressed by the most recent commit
