### ISSUE TITLE
AZ-120_Lab01b-Azure_VM_Windows_Clustering.md -- Azure changes + a couple typos (minor issues)

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#53]
Below is a listing from a recent QA run where some items have changed in Azure, are no longer available, or typos:

- **Exercise 1, Task 1, Step 4:** 'Pdc RDP Port' & 'Bdc RDP Port' do not appear as fields to populate.

- **Exercise 1, Task 2, Steps 2 + 4:** There is no option anymore for 'Enable basic plan for free' nor 'Enable backup'.

- **Exercise 2, Task 3, Step 3:** Instead of 'Replication' it is now titled 'Redundancy'.

- **Exercise 3, Task 1, Steps 7-10 & 12-15:**  Looks like typo where the VM name(s) are listed as 'az12001a-vm0' (or in 12-15, 'az12001a-vm1') where they are actually 'az12001b-cl-vm0' and 'az12001b-cl-vm1', respectively. 

- **Exercise 3, Task 2, Step 5:** There is no longer an 'Unhealthy threshhold' field to populate here.

- **Exercise 3, Task 2, Step 6:** Frontend IP address was listed as 'frontend-ip1 (10.0.1.240)' and not '192.168.0.240 (LoadBalancerFrontEnd)'

- **Exercise 3, Task 3, Step 11:** There is no longer an 'Unhealthy threshhold' field to populate here.

- **Exercise 3, Task 4, Step 3:** No longer an option for 'Enable backup' anywhere I could find.

**Comment by polichtm** [comment]
Appreciate the suggestions. This module is being rewritten to incorporate a Bicep-based deployment - more information to follow
rgds
Marcin

**Comment by TesterTesterson1004** [comment]
I'm testing using an ALHs Cloudslice platform and just noticed that in a different lab it *does* have the 'Enable basic plan for free' option to disable, so it is highly likely this is ALH-specific behavior that varies based on type of subscription in use - thus the reference here to that as an 'Azure-has-changed' issue can likely be ignored.  Apologies for red herring!

**Comment by polichtm** [comment]
addressed by the most recent commit
