### ISSUE TITLE
AZ-120_Lab1b_Implement_Windows_Clustering_on_Azure_VMs: Issue with Quickstart Template

### ISSUE THREAD

**Issue by tumultuous1** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#57]
Exercise 1: Provision Azure compute resources necessary to support highly available SAP NetWeaver deployments
Task 1: Deploy a pair of Azure VMs running highly available Active Directory domain controllers by using a Bicep template

Azure Quickstart Template fails during post-deployment configuration.  Have tried multiple times (with complex passwords), but get an error stating: "**Either the target name is incorrect or the server has rejected the client credentials**."

![Screenshot_444](https://user-images.githubusercontent.com/103527215/217652786-24f838e7-c91c-464a-b6f9-874862f3671a.png)

**Comment by polichtm** [comment]
Pls remove the extension and rerun the last two steps (as per the updated instructions)
![image](https://user-images.githubusercontent.com/10284906/217971082-60b80bc2-f265-41d6-9021-028e45ce1b95.png)

rgds
Marcin
