### ISSUE TITLE
AZ-120_Lab1b_Implement_Windows_Clustering_on_Azure_VMs: Attaching Disks to vm0 and vm1

### ISSUE THREAD

**Issue by tumultuous1** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#58]
Exercise 1: Provision Azure compute resources necessary to support highly available SAP NetWeaver deployments
Task 3: Create and configure Azure VMs disks
Steps 7-13

After creating disks via cloud shell in steps 1-6, when I get to step 7 the disks do not show up in the Azure UI under _Attach Existing Disks_.   (I can, however, _Create and attach a new disk_.)   

After much trial and error, I discovered that the disks would appear in the _Attach existing disks_ list if during the vm0 and vm1 creation process I chose **No Infrastructure redundancy required** for the _Availability options_.

I'm guessing that having the Availability options set to **No Infrastructure redundancy required** will have a negative impact on further tasks in this lab.

**Comment by polichtm** [comment]
Appreciate the feedback.
The lab is meant to illustrate a deployment across two availability zones (although the subsequent steps would actually work if you were to proceed with a regional deployment). The instructions have been updated to accommodate the original intention.
Pls give it a try when you have a chance and let us know if you run into any issues.
rgds
Marcin
