### ISSUE TITLE
AZ-120_Lab01b-Azure_VM_Windows_Clustering - Password issue suggestion

### ISSUE THREAD

**Issue by Kiyani1** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#62]
In Exercise 1 Task 1 we are asked to type a password on step 9. Moving on in Task 2 step 2 we are asked to enter the same password we used in Task 1.

In my case, I used the password **Pa55w.rd** which is not accepted when provisioning a windows server VM due to password length requirements. Can this be updated to a specific password or clearly mentioned like the password should fulfill the complexity requirement?

Not a blocking issue but a frustrating one as after we wait for the deployment to complete the next task requires the same password as before and we cannot use the same password.

### Relevant screenshots

![image](https://user-images.githubusercontent.com/98971092/227598861-9e4bed5c-514e-4b5d-b65b-b34f2a8ab87e.png)

![image](https://user-images.githubusercontent.com/98971092/227598535-3f5e2be0-0238-496e-af07-6e1596a69131.png)

**Comment by polichtm** [comment]
updated
