### ISSUE TITLE
AZ-120_Lab01b-Azure_VM_Windows_Clustering.md VNet not showing up during VM creation

### ISSUE THREAD

**Issue by Kiyani1** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#63]
Hello, the VNet is not showing up during the creation of the VM (see 1st screenshot), if I try to create another VNet with the same name it gives an error this already exists (see 3rd screenshot). Can the steps be updated to create a VM in Azure Cloud shell instead? I believe this can be resolved if we create VMs through Cloud Shell. 

### Relevant screenshots
![image](https://user-images.githubusercontent.com/98971092/228037149-0fc96505-0ee5-4c11-886b-f5741004576a.png)

![image](https://user-images.githubusercontent.com/98971092/228039151-e5f57642-9234-4f90-bea2-961e012d8ef8.png)

![image](https://user-images.githubusercontent.com/98971092/228039813-6210799f-7134-47d1-8caa-ca6edbb569fe.png)

**Comment by Kiyani1** [comment]
Facing the same issue in the next module AZ-120_Lab03a-HANA_HA_Infrastructure_Deployment.md

**az12003a-sap-vnet** does not show up immediately (see 1st screenshot), however it is already created (see 2nd screenshot)

![image](https://user-images.githubusercontent.com/98971092/228400299-1111bb68-de6f-494b-9c1a-0c39803287be.png)

![image](https://user-images.githubusercontent.com/98971092/228400662-617d0521-649b-4f1e-95f9-a622b035e67b.png)

**Comment by polichtm** [comment]
I'm not able to reproduce the issue you're running into. Have you tried restarting the VM provisioning process?
rgds
Marcin

**Comment by polichtm** [comment]
Closing due to the lack of responses
