### ISSUE TITLE
AZ-120_Lab01b-Azure_VM_Windows_Clustering.md incorrect frontend IP

### ISSUE THREAD

**Issue by Kiyani1** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#65]
In Exercise 3 Task 2 step 6 **Frontend IP address** should be updated to **frontend-ip1 (10.0.1.240)** instead of **192.168.0.240 (LoadBalancerFrontEnd)** as we created **frontend-ip1 (10.0.1.240)** in step 2.

### Relevant screenshots

![image](https://user-images.githubusercontent.com/98971092/228086281-3b48fb19-296e-48bc-a94c-96417fdc4b5d.png)

**Comment by polichtm** [comment]
Valid point - updated
rgds
Marcin
