### ISSUE TITLE
AZ 120 Module 4: Deploy SAP on Azure issues

### ISSUE THREAD

**Issue by kumud-sharma** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#66]
# Module/Lab: AZ 120 Module 4: Deploy SAP on Azure
#### Step: 03

Description of issue
 The lab guide mentions "cluster status is healthy". If you are seeing a message indicating that one of two cluster nodes is unclean, restart that node from the Azure portal. we did this part but still cluster status is not healthy.

### Relevant screenshots
![image](https://user-images.githubusercontent.com/33771500/228558145-e59cc9eb-a1e0-41f6-8eae-69ae7b691608.png)

**Comment by polichtm** [comment]
Hi Kumud
unfortunately I'm not able to reproduce this issue. The outcome in your case seems to imply that the fencing resource is misconfigured. Have you verified that the resource is fully operational?
rgds
Marcin

**Comment by akn9050** [comment]
Thanks @polichtm for quick turn around on this, we will retest and check it.

**Comment by polichtm** [comment]
Pls let us know if you're still running into this issue
rgds
Marcin
