### ISSUE TITLE
AZ-120_Lab03a-HANA_HA_Infrastructure_Deployment.md - Unable to SSH to i20-db-1

### ISSUE THREAD

**Issue by Kiyani1** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#67]
Hello, when I try to connect to **i20-db-1** VM from **i20-db-0** using ssh **root@i20-db-1** it always asks me for a password even after I have pasted the key in authorized keys see the attached screenshot. Can anyone tell me what I might be doing wrong?

Although I was able to successfully connect to **i20-db-0** from **i20-db-1**.

### Relevant screenshots
![image](https://user-images.githubusercontent.com/98971092/228696731-fb79c833-28db-478a-ad0c-d28b3664f2ad.png)

**Comment by HashirSajjad** [comment]
Hi, Is there any update on this issue?

**Comment by polichtm** [comment]
Unfortunately I'm not able to reproduce this issue.  Pls let me know if you're still running into it.
rgds
Marcin
