### ISSUE TITLE
AZ-120_Lab03a-HANA_HA_Infrastructure_Deployment.md - Template deployment issues

### ISSUE THREAD

**Issue by Kiyani1** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#68]
I'm unable to complete the deployment successfully at **Exercise 1, Task 2** Whenever I delete the Custom script and redeploy the template the Custom script always gets created again (see 3rd Screenshot). Any suggestions?

### Relevant screenshots

![image](https://user-images.githubusercontent.com/98971092/229171372-e144981b-6bac-4727-a9c9-7699c2ee63ed.png)

![image](https://user-images.githubusercontent.com/98971092/229171809-732ce1b7-0866-4b20-bf08-151a30ec2efc.png)

![image](https://user-images.githubusercontent.com/98971092/229171831-d974d678-a9c3-48e8-a159-f28e518bddd3.png)

![image](https://user-images.githubusercontent.com/98971092/229171904-dba67031-ae01-4dda-95cc-5ab341bf7469.png)

**Comment by HashirSajjad** [comment]
Hello, Is there any update on this issue?

**Comment by polichtm** [comment]
Hi Hashir,
investigating...
rgds
Marcin

**Comment by polichtm** [comment]
this has been addressed
rgds
Marcin
