### ISSUE TITLE
Lab 3a: Implement SAP architecture on Azure VMs running Linux - issue

### ISSUE THREAD

**Issue by bonzz** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#7]
Hi All,

While working on Lab 3a: Implement SAP architecture on Azure VMs running Linux,
In Exercise 1, Task 2
The template deployment is failing and the corresponding image showing the error is attached.

![image](https://user-images.githubusercontent.com/48308835/93790801-13070880-fc51-11ea-9d82-5e0ef0632704.png)

Can u please look into this.
Thanks & Regards

**Comment by polichtm** [comment]
Pls perform the following steps:

- review the deployment details and identify the VM(s) where the installation of the CustomScriptExtension failed (according to the screenshot, that's i20-db0 and i20-db1 in your case)
- in the Azure portal, navigate to the blade of the VM(s) you identified in the previous step, select Extensions, and from the Extensions blade, remove the CustomScript extension
- in the Azure portal, navigate to the AZ12003A-SAP-RG resource group blade, select Deployments, select the link to the failed deployment, and select Redeploy
- to redeploy, you will need to select the target resource group (AZ12003A-SAP-RG) and provide the password for the root account (Pa55w.rd1234).

rgds
Marcin

**Comment by bonzz** [comment]
Hi,
Thank you for the suggestions and it helped to complete the lab.
if possible, Can u please update these steps in the lab guide.

Thanks & Regards

**Comment by polichtm** [comment]
good to see - certainly will do so shortly
rgds
Marcin
