### ISSUE TITLE
AZ-120_Lab03a-HANA_HA_Infrastructure_Deployment.md

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#75]
# Module/Lab: 04a
#### Step: 00

Description of issue

Deploy failing, appears as if some of the parameters specified are no longer valid.

Repro steps:

Take course instructions as specified, whatif deploy (and attempting to deploy it for real) yields errors:

whatif:
![image](https://github.com/MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads/assets/49700217/db1dceba-cd66-4459-847b-d7ff49e276a2)

real deploy is same:
![image](https://github.com/MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads/assets/49700217/af388788-cd02-480d-b438-05d5b9ea9097)

I tried converting the main.bicep to a json, used it and the 3a parameters file to attempt a manual deploy/see more detailed errors in that scenario, as expected basically the same:

![image](https://github.com/MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads/assets/49700217/dcff52f0-77f4-4131-ba38-6c5cebd2eba8)

**Comment by polichtm** [comment]
updated to SLES 15
rgds
Marcin

**Comment by TesterTesterson1004** [comment]
Thanks, that helps - although now I am redoing my QA I am running into an issue later in the instructions I suspect might be related to the new VM images this may have required?  

In Exercise 2, Task 5, Step  3, '_Add YaST packages.._.' I am not entirely sure how to '_verify that Public Cloud Module is already installed_'.  I think that this result means it is **not** installed, and at least initially I am not finding a step-by-step via Google that allows me to install it successfully:

![image](https://github.com/MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads/assets/49700217/8c3915b7-989e-44e4-89bf-8c5726dc4d42)

If I ignore that and try and proceed with the lab, I suspect the lack of any updates or actions in the subsequent 'zypper' steps indicates the lack of 'public cloud module' may be preventing that from succeeding?

![image](https://github.com/MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads/assets/49700217/427860f1-119d-49ee-889a-4568da648434)

Tried to go a step or two further, but this looks like we are off the rails:

![image](https://github.com/MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads/assets/49700217/16705928-198b-4241-8190-d9d44f150e82)

Uncertain how to proceed with this lab for an End-To-End success.....

**Comment by polichtm** [comment]
investigating
rgds
Marcin

**Comment by polichtm** [comment]
This is resolved
rgds
Marcin

**Comment by TesterTesterson1004** [comment]
Excellent thanks very much- confirmed, was just able to QA past this part, and to completion.
