### ISSUE TITLE
Lab 3b: Implement SAP architecture on Azure VMs running Windows

### ISSUE THREAD

**Issue by bonzz** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#8]
Lab 3b: Implement SAP architecture on Azure VMs running Windows

In Exercise 1: Provision Azure resources necessary to support highly available SAP NetWeaver deployments

Task 5: Deploy the Scale-Out File Server (SOFS) cluster

Here the deployment prolonged as not expected and also the deployment got failed

![image](https://user-images.githubusercontent.com/48308835/93811669-24124280-fc6e-11ea-88d0-af9d9f283979.png)

Can you please look into it.

Thanks & Regards

**Comment by polichtm** [comment]
Pls perform the following steps:

- review the deployment details and identify the VM(s) where the installation of the CustomScriptExtension failed (according to the screenshot, that's i20-s2d-0 in your case)
- in the Azure portal, navigate to the blade of the VM(s) you identified in the previous step, select Extensions, and from the Extensions blade, remove the CustomScript extension
- in the Azure portal, navigate to the AZ12003B-SAP-RG resource group blade, select Deployments, select the link to the failed deployment, and select Redeploy
- to redeploy, you will need to select the target resource group (AZ12003B-SAP-RG) and provide the password for the root account (Pa55w.rd1234).

rgds
Marcin

**Comment by bonzz** [comment]
Hi,
Thank you for the suggestions and it helped to complete the lab.
if possible, Can u please update these steps in the lab guide.

Thanks & Regards
Bony

**Comment by polichtm** [comment]
Hi Bony - certainly - will do so shortly
rgds
Marcin
