### ISSUE TITLE
Lab:AZ-120_Lab06b-ACSS_One_Day "Enable replication failed"

### ISSUE THREAD

**Issue by ahsan296** [MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads#93]
# Module/Lab:AZ-120_Lab06b-ACSS_One_Day
#### Step: 18

**Description of issue:**
When I attempt to enable replication, I encounter an error. The screenshot below illustrates the errors that occurred during the processing. Because of these errors, I am unable to successfully complete the task.

### Relevant screenshots
![image](https://github.com/MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads/assets/142339674/e97b7399-71db-4221-a273-b4a6da12112b)

**Comment by eric-camplin** [comment]
@ahsan296  - thank you for the detailed feedback.  Was this lab performed in a provider hosted lab environment, using your private azure account or with an Azure Pass?  Also, note that this lab 6b had not been released for any course at this point due to its length.

**Comment by ahsan296** [comment]
We are affiliated with a lab hosting company and utilize our own private Azure subscription for this.

**Comment by eric-camplin** [comment]
Lab 6b is no longer supported please use lab 6A or the favored lab 6C

**Comment by ahsan296** [comment]
Hi thanks for updating.

Thank You!

Regards,
Hafiz M. Ahsan
Content QA Engineer,
Xtremelabs LLC.


________________________________
